# Generated by Django 4.2.30 on 2026-09-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자산명')),
                ('category', models.CharField(choices=[('real_estate', '부동산'), ('deposit', '예금·적금'), ('securities', '주식·펀드'), ('insurance', '보험'), ('vehicle', '차량·장비'), ('cash', '현금성자산'), ('other', '기타')], default='other', max_length=20, verbose_name='분류')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='평가금액')),
                ('acquired_on', models.DateField(blank=True, null=True, verbose_name='취득일')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-amount', '-created_at'],
            },
        ),
    ]
